### ISSUE TITLE
Trying to use GFPGAN gives an Runtime Error - (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

### ISSUE THREAD

**Issue by NitorikoSkye** [hlky/stable-diffusion#130]
![image](https://user-images.githubusercontent.com/112488787/187442085-afa3cca0-1bdf-43d9-a458-81296bd8a86c.png)
After the last update, whenever I try to use GFPGAN it ends up giving the following error, both in img2img and txt2img.
I use the following code in **relauncher.py**
`    os.system("python scripts/webui.py --precision full --no-half --gfpgan-cpu --esrgan-cpu --optimized")
`
I've tried reinstalling it, removing the environment and even reinstalling miniconda entirely, but nothing has helped me with this issue.
GPU is GTX 1660 Ti 6GB.

**Comment by hlky** [comment]
You could try using gfpgan on it's standalone tab as post-processing, and also try removing the model file for esrgan so that doesn't load, I suppose I should add an option to disable loading each of the extra models all together but you can do the same thing for now by just deleting (or moving) the appropriate .pth model file

6gb is towards the lower end of the absolute bare minimum requirements though so issues with OOM are to be expected really.
